### ISSUE TITLE
Enable Sign in with Apple

### ISSUE THREAD

**Issue by Supereg** [StanfordBDHG/NAMS#34]
### Problem

We just updated to the newest release of SpeziAccount (see #33). However, we haven't enabled Sign in with Apple yet. This requires some additional setup in the provisioning profile and on the Firebase side of things.

### Solution

Setup Sign in with Apple according to the [Firebase Guide](https://firebase.google.com/docs/auth/ios/apple).
* Setting up the Provisioning Profile on the Apple Developer website.
* Complete configuration in the Firebase project.
* Add the Sign in with Apple entitlement to the project.
* Update the App's FirebaseAccountConfiguration to enable the Sign in with Apple button.

### Additional context

CC: @PSchmiedmayer maybe we can tackle this in the next few days.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by Supereg** [comment]
Resolved as of #39

**Comment by PSchmiedmayer** [comment]
Great job @Supereg! 🚀
